[package]
name = "ntp-daemon"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.19.1", features = ["full"] }
futures = "0.3.21"
ntp-proto = { path = "../ntp-proto" }
ntp-os-clock = { path = "../ntp-os-clock" }
ntp-udp = { path = "../ntp-udp" }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["env-filter", "serde"] }
clap = { version = "3.1.18", features = ["derive", "env"] }
toml = "0.5.9"
thiserror = "1.0.31"
serde = { version = "1.0.137", features = ["derive"] }
sentry = { version = "0.26.0", optional = true }
sentry-tracing = { version = "0.26.0", optional = true }

[features]
sentry = ["dep:sentry", "dep:sentry-tracing"]
