[package]
name = "ntp-daemon"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.19.2", features = ["full"] }
ntp-proto = { path = "../ntp-proto" }
ntp-os-clock = { path = "../ntp-os-clock" }
ntp-udp = { path = "../ntp-udp" }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.14", features = ["env-filter", "serde", "json"] }
clap = { version = "3.2.8", features = ["derive", "env"] }
toml = "0.5.9"
thiserror = "1.0.31"
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
sentry = { version = "0.27.0", optional = true }
sentry-tracing = { version = "0.27.0", optional = true }

[dev-dependencies]
ntp-proto = { path = "../ntp-proto", features=["ext-test"]}

[features]
sentry = ["dep:sentry", "dep:sentry-tracing"]
